const types = {
    CALCULATOR_UPDATE_SUM_FIRST: 'CALCULATOR_UPDATE_SUM_FIRST',
    CALCULATOR_UPDATE_SUM_SECOND: 'CALCULATOR_UPDATE_SUM_SECOND',
    INFORMATION_UPDATE_USER_NAME: 'INFORMATION_UPDATE_USER_NAME',
    INFORMATION_UPDATE_USER_BIRTHDAY: 'INFORMATION_UPDATE_USER_BIRTHDAY',
};

export default types;
